### PR TITLE
Pollution Plot

### PR DESCRIPTION
**Pull request by autermann**
Restrictions: currently only the first timeseries will be plottet, and only if there is wind data available for that time

### CODE REVIEW

**Comment by autermann** [comment]
Query string for valid data: `ts=ts_20130d3498806172d5aaae917211e2ef__irceline,ts_d5d66c4140a5762367c07e24e77e9135__irceline&span=2015-01-27T05:44:06+01:00/2015-01-28T05:44:05+01:00#analysis`

**Comment by nuest** [comment]
Where (city) is the station that is working for that time span?

**Comment by nuest** [comment]
I get an error message:

```
Error in findNearestStation(station(ts)) : 
  could not find function "nearest"
```

I installed `sensorweb4R` from GitHub (52North/master)

**Comment by autermann** [comment]
> I get an error message:
> 
> Error in findNearestStation(station(ts)) : 
>   could not find function "nearest"
>

Can't reproduce that:

```r
devtools::install_github("52North/sensorweb4R")
library(sensorweb4R)
nearest
```
```
standardGeneric for "nearest" defined from package "sensorweb4R"

function (x, all, dm = NULL, n = 1, ...) 
standardGeneric("nearest")
<environment: 0x0000000012feb678>
Methods may be defined for arguments: x, all, dm, n
Use  showMethods("nearest")  for currently available ones.
```
```r
showMethods("nearest")
```
```
Function: nearest (package sensorweb4R)
x="Station", all="missing"
x="Station", all="Station"
```
> and when requesting an analysis:
> 
> Fehler bei der Auswertung des Argumentes 'i' bei der Methodenauswahl für Funktion '[': Error in station(ts) == sta.near : comparison (1) is possible only for atomic and list types
> I installed sensorweb4R from GitHub (52North/master)

Forgot to merge a branch. Fixed.

**Comment by nuest** [comment]
Ok, works now. Added some more documentation to the readme, see https://github.com/autermann/sensorweby/pull/1

**Pull request merged**
